name: Build iOS version

on:
  # push:
    # branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
# concurrency:
  # group: "pages"
  # cancel-in-progress: false

jobs:
  publish:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - name: check out to main branch
        uses: actions/checkout@v4.1.7

      - name: setup Flutter and build
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.1
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build ipa
